[project]
name = "spn4re-nerel"
version = "0.1.0"
description = "SPN4RE on NEREL"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.1.1",
    "datasets>=3.1.0",
    "scipy>=1.14.1",
    "torch>=2.5.1",
    "tqdm>=4.67.0",
    "transformers==2.6.0",
]
